<a href="https://colab.research.google.com/github/CrystalYang108/disasterdata/blob/main/disastersdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loading/reading data file

In [ ]:
import pandas as pd
import plotly as py
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot
import plotly.graph_objs as go
df = pd.read_csv('https://raw.githubusercontent.com/CrystalYang108/disasterdata/main/DisasterDeclarationsSummaries.csv')
df.head()

,femaDeclarationString,disasterNumber,state,declarationType,declarationDate,fyDeclared,incidentType,declarationTitle,ihProgramDeclared,iaProgramDeclared,...,disasterCloseoutDate,fipsStateCode,fipsCountyCode,placeCode,designatedArea,declarationRequestNumber,lastIAFilingDate,hash,id,lastRefresh
0,FM-5444-TX,5444,TX,FM,2022-07-19T00:00:00.000Z,2022,Fire,CHALK MOUNTAIN FIRE,0,0,...,NaN,48,221,99221,Hood (County),22060,NaN,373c5ec27998afc08a53302dae796f476b1a6546,867be42a-71d5-4f13-aa21-d91e0a6fd577,2022-07-20T21:21:23.941Z
1,FM-5436-NE,5436,NE,FM,2022-04-23T00:00:00.000Z,2022,Fire,ROAD 702 FIRE,0,0,...,NaN,31,63,99063,Frontier (County),22034,NaN,ea3487ef36cff455236ce4c63d32fb8b5412bcef,e671348b-9782-42df-99f4-d38b8b1a89e6,2022-07-20T21:21:23.942Z
2,FM-5444-TX,5444,TX,FM,2022-07-19T00:00:00.000Z,2022,Fire,CHALK MOUNTAIN FIRE,0,0,...,NaN,48,425,99425,Somervell (County),22060,NaN,1f35dd8137e1b4cf003fb73d53d8aaaf642e6190,40f3ff75-0b80-4d25-8e85-156cd6a6f40b,2022-07-20T21:21:23.943Z
3,FM-5436-NE,5436,NE,FM,2022-04-23T00:00:00.000Z,2022,Fire,ROAD 702 FIRE,0,0,...,NaN,31,65,99065,Furnas (County),22034,NaN,9d813a845ab86f546bdf642fda53d3d4a0fbd098,de47838f-32db-4058-a34c-64997333789e,2022-07-20T21:21:23.943Z
4,FM-5436-NE,5436,NE,FM,2022-04-23T00:00:00.000Z,2022,Fire,ROAD 702 FIRE,0,0,...,NaN,31,145,99145,Red Willow (County),22034,NaN,d436856ce1d5205fa78597b93661fb27d3cea796,483c03b7-160a-414e-bb4f-5ccecc18d94a,2022-07-20T21:21:23.944Z

Creating new dataframe to have only those columns,
Creating new dataframe where only columns with specific indcident type and specific year

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/CrystalYang108/disasterdata/main/DisasterDeclarationsSummaries.csv')
df2=df[['fyDeclared','state','fipsStateCode','incidentType','disasterNumber']]
df2=df2[(df2['incidentType']=='Flood') & (df['fyDeclared']==2022)]
df2.head()

     fyDeclared state  fipsStateCode incidentType  disasterNumber
499        2022    MN             27        Flood            4659
527        2022    MN             27        Flood            4659
528        2022    MN             27        Flood            4659
529        2022    MN             27        Flood            4659
535        2022    MT             30        Flood            4655

Drops duplicate values such as repeated states with the same incident type and disaster number values

In [ ]:
df_dup = df2.drop_duplicates(subset=["state"])
df_dup.head(10)

       fyDeclared state  fipsStateCode incidentType  disasterNumber
499          2022    MN             27        Flood            4659
535          2022    MT             30        Flood            4655
557          2022    WA             53        Flood            4650
658          2022    PR             72        Flood            4649
920          2022    NH             33        Flood            4624
976          2022    VA             51        Flood            4628
57655        2022    MO             29        Flood            4665
58394        2022    KY             21        Flood            4663

Visualization of new dataframe

In [ ]:
import plotly.express as py
fig = py.choropleth(df_dup,
                    locations='state', 
                    locationmode="USA-states", 
                    scope="usa",
                    color='disasterNumber',
                    color_continuous_scale="blues", 
                    title = 'Number of Floods in the United States 2022'
                    
                    )
fig.show()